title: SentienceMUD Builder Guide
description: OLC Documentation for SentienceMUD
theme: just-the-docs

color_scheme: dark

url: https://olc.sentiencemud.net

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_external_links:
 - title: "Immortal Guide"
   url: https://immguide.sentiencemud.net
   hide-icon: true
 - title: "Player Guide"
   url: https://playerguide.sentiencemud.net
   hide-icon: true