title: SentienceMUD Builder Guide
description: OLC Documentation for SentienceMUD
theme: just-the-docs

color_scheme: dark

url: https://olc.sentiencemud.net

aux_links:
  Main Site: https://sentiencemud.net
  Discord: https://discord.gg/E2Ahw5Xy

nav_external_links:
 - title: "Immortal Guide"
   url: https://immguide.sentiencemud.net
   hide-icon: true
 - title: "Player Guide"
   url: https://playerguide.sentiencemud.net
   hide-icon: true